#! /bin/bash

dotfiles_dir="$HOME/.dotfiles"
ssh_dir="$HOME/.ssh"
gpg_dir="$HOME/.gnupg"
homebrew_url="https://raw.githubusercontent.com/Homebrew/install/master/install"
spacemacs_url="https://github.com/syl20bnr/spacemacs"
kiex_url="https://raw.githubusercontent.com/taylor/kiex/master/install"

if [ ! -f $ssh_dir/id_rsa ]; then
  echo "Setup $ssh_dir before proceeding."
  exit 1
fi

chmod 700 $ssh_dir
chmod 600 $ssh_dir/*

if [ ! -f $gpg_dir/secring.gpg ]; then
  echo "Setup $gpg_dir before proceeding."
  exit 1
fi

chmod 700 $gpg_dir
chmod 600 $gpg_dir/*

echo "Creating Developer directory."
mkdir -p $HOME/Developer

if [ ! -d $dotfiles_dir ]; then
  echo "Installing (git-based) dotfiles"
  git clone git@github.com:mrrooijen/dotfiles.git $dotfiles_dir
fi

echo "Linking (git-based) dotfiles: emacs, bash, git, ruby."
ln -nfs "$dotfiles_dir/emacs/spacemacs"    "$HOME/.spacemacs"
ln -nfs "$dotfiles_dir/bash/inputrc"       "$HOME/.inputrc"
ln -nfs "$dotfiles_dir/bash/bashrc"        "$HOME/.bashrc"
ln -nfs "$dotfiles_dir/bash/bash_profile"  "$HOME/.bash_profile"
ln -nfs "$dotfiles_dir/git/gitconfig"      "$HOME/.gitconfig"
ln -nfs "$dotfiles_dir/ruby/gemrc"         "$HOME/.gemrc"

echo "Installing xcode command-line tools"
xcode-select --install

echo "Installing homebrew"
/usr/bin/ruby -e "$(curl -fsSL $homebrew_url)"

echo "Tapping into caskroom/cask"
brew tap caskroom/cask

echo "Installing gpg"
brew install gpg

echo "Installing git"
brew install git

echo "Installing emacs"
brew cask install emacs pinentry-mac

if [ ! -d "$HOME/.emacs.d" ]; then
  git clone $spacemacs_url $HOME/.emacs.d
fi

echo "Installing rvm"
gpg --keyserver hkp://keys.gnupg.net \
    --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
curl -sSL https://get.rvm.io | bash -s stable

echo "Installing kiex"
curl -sSL $kiex_url | bash -s

echo "Installing spectacle"
brew cask install spectacle
