# General

stty sane
autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
setopt auto_cd
HISTFILE=~/.zsh_history
HISTSIZE=1000
SAVEHIST=1000
setopt SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
export PROMPT="%~ # "

# Aliases

alias reload="source $HOME/.zshrc"
alias flushcache="sudo killall -HUP mDNSResponder"

# Local Scripts

export PATH="$HOME/bin/bin:$PATH"

}

# Ruby

export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
export PATH="/opt/homebrew/lib/ruby/gems/3.1.0/bin:$PATH"
source /opt/homebrew/opt/chruby/share/chruby/chruby.sh
source /opt/homebrew/opt/chruby/share/chruby/auto.sh

# Emacs

export EMACS="/Applications/Emacs.app/Contents/MacOS/Emacs"
export EDITOR="/opt/homebrew/bin/emacsclient -c"

# Local zsh configuration

[ -s ~/.zshrc.local ] && source ~/.zshrc.local
