source $HOME/.dotfiles/zsh/include_zshrc/options
source $HOME/.dotfiles/zsh/include_zshrc/variables
source $HOME/.dotfiles/zsh/include_zshrc/prompt
source $HOME/.dotfiles/zsh/include_zshrc/mise
source $HOME/.dotfiles/zsh/include_zshrc/seatbelt
source $HOME/.dotfiles/zsh/include_zshrc/hold_microphone
source $HOME/.dotfiles/zsh/include_zshrc/local
