# General

autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
setopt auto_cd
HISTFILE=~/.zsh_history
HISTSIZE=1000
SAVEHIST=1000
setopt SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
export PROMPT="%~ # "

# Aliases

alias reload="source $HOME/.zshrc"
alias flushcache="sudo killall -HUP mDNSResponder"

# Local Scripts

export PATH="$HOME/bin/bin:$PATH"

# Security Key (Yubikey)

alias key-kill="gpg-connect-agent 'scd serialno' 'learn --force' /bye"
alias key-set-touch-aut="ykman openpgp keys set-touch aut"
alias key-set-touch-sig="ykman openpgp keys set-touch sig"
alias key-set-touch-enc="ykman openpgp keys set-touch enc"

function key-set-touch() {
    echo "Enter admin pin:"
    read -s pin
    echo "$pin\ny\n" | key-set-touch-sig $1 || return
    echo
    echo "$pin\ny\n" | key-set-touch-enc $1 || return
    echo
    echo "$pin\ny\n" | key-set-touch-aut $1 || return
    echo
    ykman openpgp info
}

# Ruby

export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="/usr/local/lib/ruby/gems/3.0.0/bin:$PATH"
source /usr/local/opt/chruby/share/chruby/chruby.sh 2> /dev/null
source /usr/local/opt/chruby/share/chruby/auto.sh 2> /dev/null

# Emacs

export EMACS="/Applications/Emacs.app/Contents/MacOS/Emacs"
export EDITOR=$EMACS
alias emacs="$EMACS -nw"

# Local zsh configuration

[ -s ~/.zshrc.local ] && source ~/.zshrc.local
