#! /bin/bash

parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export HISTFILE=~/.bash_history
export HISTSIZE=25
export HISTTIMEFORMAT="%F %T | "
export EDITOR="emacs -nw"
export GIT_EDITOR=vim
export GPG_TTY=$(tty)
export GOPATH=$HOME/Developer/Go
export PS1="\[\033[32m\]\w\[\033[33m\]\$(parse_git_branch)\[\033[00m\] $ "

source ~/.bashrc
[ -s ~/.bashrc.local ] && source ~/.bashrc.local
