#! /bin/bash

alias ls="ls -G"

if [ -f "/usr/local/opt/chruby/share/chruby/chruby.sh" ]; then
  source /usr/local/opt/chruby/share/chruby/chruby.sh
  source /usr/local/opt/chruby/share/chruby/auto.sh
fi

if [ -f "$HOME/.kiex/scripts/kiex" ]; then
  source "$HOME/.kiex/scripts/kiex"
fi
